language: python
python:
  - "3.7-dev"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy2.7"
  - "pypy3.5"

before_install:
  - pip install coverage
  - pip install codecov

script:
  - "./run-test-coverage.py"

after_success:
  - codecov

notifications:
      email: false
