language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"

before_install:
  - pip install coverage
  - pip install codecov

script:
  - "./run-test-coverage.py"

after_success:
  - codecov

notifications:
      email: false
